nusc_exp_mgr_node:
  ros__parameters:
    exp_configs: ['config/nusc_baseline.yaml']
                  
    val_dataset: 'v1.0-mini'
    val_split: 'mini_val'
    mcap_dir: 'nuscenes/mcap' # relative to home directory
    results_dir: 'tracking_ws/src/marmot/results' # relative to home directory
    det_topic: '/detections'
    track_topic: '/tracks'
    lidar_detector: 'megvii'